export const ACTION_TRANSPORTER = 'ACTION_TRANSPORTER';
export const ACTION_SELF_INFO = 'ACTION_SELF_INFO';
export const ACTION_LIVE = 'ACTION_LIVE';
export const ACTION_CLUSTER_INFO = 'ACTION_CLUSTER_INFO';
export const ACTION_GET_CLUSTER_INFO = 'ACTION_GET_CLUSTER_INFO';
