export const DEFAULT_KAKKA_APPLICATION_NAME = 'default_hokku_application';
export const DEFAULT_KAKKA_SERVICE_NAME = 'default_hokku_service';
export const DEFAULT_KAKKA_DISCOVERY_BEACON_PORT = 17707;
export const DEFAULT_KAKKA_DISCOVERY_IP_VERSION = 4;
export const DEFAULT_KAKKA_DISCOVERY_PIPE_PORT = 17717;
export const DEFAULT_KAKKA_DISCOVERY_PIPE_PREFIX = '';
export const DEFAULT_KAKKA_ACTION_GATE_HOST = 'localhost';
export const DEFAULT_KAKKA_ACTION_GATE_PORT = 17727;
