export const DEFAULT_HOKKU_APPLICATION_NAME = 'default_hokku_application';
export const DEFAULT_HOKKU_SERVICE_NAME = 'default_hokku_service';
export const DEFAULT_HOKKU_DISCOVERY_BEACON_PORT = 17707;
export const DEFAULT_HOKKU_DISCOVERY_IP_VERSION = 4;
export const DEFAULT_HOKKU_DISCOVERY_PIPE_PORT = 17717;
export const DEFAULT_HOKKU_DISCOVERY_PIPE_PREFIX = '';
export const DEFAULT_HOKKU_ACTION_GATE_HOST = 'localhost';
export const DEFAULT_HOKKU_ACTION_GATE_PORT = 17727;
